from __future__ import annotations

import argparse
import json
import re
import sys
from typing import Any

from recordwise_common import CONFIGS, GENERATED, REPORTS, read_json, write_json, write_log


def sv_name(name: str) -> str:
    cleaned = re.sub(r"[^A-Za-z0-9_]", "_", name).upper()
    if cleaned and cleaned[0].isdigit():
        cleaned = "_" + cleaned
    return cleaned


def integer_like(value: Any) -> bool:
    return isinstance(value, bool) or (isinstance(value, int) and not isinstance(value, bool))


def write_sv_package(snapshot: dict[str, Any], final: dict[str, Any]) -> None:
    GENERATED.mkdir(parents=True, exist_ok=True)
    pkg = GENERATED / "recordwise_params_pkg.sv"
    vh = GENERATED / "recordwise_params.vh"
    lines = [
        "// Auto-generated by tools/recordwise/export_params_for_rtl.py",
        "// Strict record-wise parameters are exported for review/XSim integration.",
        "// Current RTL is not automatically rewired by this file.",
        "package recordwise_params_pkg;",
    ]
    defines = [
        "`ifndef RECORDWISE_PARAMS_VH",
        "`define RECORDWISE_PARAMS_VH",
        "// Auto-generated by tools/recordwise/export_params_for_rtl.py",
    ]
    for group, params in [("SNAPSHOT", snapshot), ("FINAL", final)]:
        lines.append(f"  // {group} parameters")
        defines.append(f"// {group} parameters")
        for key, value in sorted(params.items()):
            param = f"STRICT_RW_{group}_{sv_name(key)}"
            if integer_like(value):
                intval = int(value)
                lines.append(f"  localparam integer {param} = {intval};")
                defines.append(f"`define {param} {intval}")
            else:
                encoded = json.dumps(value, ensure_ascii=False)
                lines.append(f"  // {param} = {encoded}")
                defines.append(f"// {param} = {encoded}")
    lines.append("endpackage")
    defines.append("`endif")
    pkg.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
    vh.write_text("\n".join(defines).rstrip() + "\n", encoding="utf-8")


def write_summary(outputs: list[str]) -> Any:
    path = REPORTS / "rtl_param_export_summary.md"
    lines = [
        "# Strict Record-wise RTL Parameter Export Summary",
        "",
        "Locked strict record-wise parameters were exported for Python/XSim/RTL handoff.",
        "",
        "| output | role |",
        "|---|---|",
        "| `generated/recordwise_params_pkg.sv` | SystemVerilog package-style integer parameter export |",
        "| `generated/recordwise_params.vh` | Verilog include-style integer macro export |",
        "| `configs/recordwise/best_params_for_python.json` | Python evaluation handoff copy |",
        "| `configs/recordwise/best_params_for_xsim.json` | XSim integration handoff copy |",
        "",
        "## Integration Boundary",
        "",
        "The existing RTL is not fully parameterized against this generated file. The export is a traceable handoff artifact; wiring the selected strict record-wise parameters into RTL/XSim remains a controlled integration TODO unless a downstream script explicitly includes these files.",
        "",
        "## Outputs",
        "",
    ]
    lines.extend(f"- `{item}`" for item in outputs)
    path.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
    return path


def main() -> None:
    parser = argparse.ArgumentParser(description="Export locked strict record-wise params for Python/XSim/RTL handoff.")
    parser.parse_args()

    locked_path = CONFIGS / "best_strict_recordwise_params_locked.json"
    locked = read_json(locked_path)
    snapshot = locked["selected_snapshot_params"]["params"]
    final = locked["selected_final_membrane_params"]["params"]
    write_sv_package(snapshot, final)
    py_path = CONFIGS / "best_params_for_python.json"
    xsim_path = CONFIGS / "best_params_for_xsim.json"
    payload = {
        "source": str(locked_path),
        "test_used_for_selection": False,
        "snapshot_params": snapshot,
        "final_membrane_params": final,
        "integration_note": "Generated export only; existing RTL include/integration is a TODO unless explicitly wired.",
    }
    write_json(py_path, payload)
    write_json(xsim_path, payload)
    outputs = [
        "generated/recordwise_params_pkg.sv",
        "generated/recordwise_params.vh",
        "configs/recordwise/best_params_for_python.json",
        "configs/recordwise/best_params_for_xsim.json",
    ]
    summary = write_summary(outputs)
    write_log(
        "export_params_for_rtl",
        sys.argv,
        [GENERATED / "recordwise_params_pkg.sv", GENERATED / "recordwise_params.vh", py_path, xsim_path, summary],
        {"rtl_auto_integrated": False},
    )
    print(summary)


if __name__ == "__main__":
    main()
